config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses_groups
  resources :groups do
  resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "groups#index"
end

app/models/expenses_group.rb
class ExpensesGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/controllers/expenses_groups_controller.rb
class ExpensesGroupsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_expenses_group, only: %i[show edit update destroy]

  # GET /expenses_groups or /expenses_groups.json
  def index
    @expenses_groups = ExpensesGroup.all
  end

  # GET /expenses_groups/1 or /expenses_groups/1.json
  def show; end

  # GET /expenses_groups/new
  def new
    @expenses_group = ExpensesGroup.new
  end

  # GET /expenses_groups/1/edit
  def edit; end

  # POST /expenses_groups or /expenses_groups.json
  def create
    @expenses_group = ExpensesGroup.new(expenses_group_params)

    respond_to do |format|
      if @expenses_group.save
        format.html { redirect_to expenses_group_url(@expenses_group), notice: 'Expenses group was successfully created.' }
        format.json { render :show, status: :created, location: @expenses_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expenses_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses_groups/1 or /expenses_groups/1.json
  def update
    respond_to do |format|
      if @expenses_group.update(expenses_group_params)
        format.html { redirect_to expenses_group_url(@expenses_group), notice: 'Expenses group was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenses_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenses_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses_groups/1 or /expenses_groups/1.json
  def destroy
    @expenses_group.destroy

    respond_to do |format|
      format.html { redirect_to expenses_groups_url, notice: 'Expenses group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expenses_group
    @expenses_group = ExpensesGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expenses_group_params
    params.require(:expenses_group).permit(:expense_id, :group_id)
  end
end

app/helpers/expenses_groups_helper.rb
module ExpensesGroupsHelper
end

app/views/expenses_groups/_expenses_group.html.erb
<div id="<%= dom_id expenses_group %>">
  <p>
    <strong>Expense:</strong>
    <%= expenses_group.expense_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= expenses_group.group_id %>
  </p>

</div>

app/views/expenses_groups/_form.html.erb
<%= form_with(model: expenses_group) do |form| %>
  <% if expenses_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expenses_group.errors.count, "error") %> prohibited this expenses_group from being saved:</h2>

      <ul>
        <% expenses_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :expense_id, style: "display: block" %>
    <%= form.text_field :expense_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses_groups/edit.html.erb
<h1>Editing expenses group</h1>

<%= render "form", expenses_group: @expenses_group %>

<br>

<div>
  <%= link_to "Show this expenses group", @expenses_group %> |
  <%= link_to "Back to expenses groups", expenses_groups_path %>
</div>

app/views/expenses_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses groups</h1>

<div id="expenses_groups">
  <% @expenses_groups.each do |expenses_group| %>
    <%= render expenses_group %>
    <p>
      <%= link_to "Show this expenses group", expenses_group %>
    </p>
  <% end %>
</div>

<%= link_to "New expenses group", new_expenses_group_path %>

app/views/expenses_groups/new.html.erb
<h1>New expenses group</h1>

<%= render "form", expenses_group: @expenses_group %>

<br>

<div>
  <%= link_to "Back to expenses groups", expenses_groups_path %>
</div>

app/views/expenses_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expenses_group %>

<div>
  <%= link_to "Edit this expenses group", edit_expenses_group_path(@expenses_group) %> |
  <%= link_to "Back to expenses groups", expenses_groups_path %>

  <%= button_to "Destroy this expenses group", @expenses_group, method: :delete %>
</div>