config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses_groups
  resources :groups do
  resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "groups#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  def total_amount
    expenses.includes(:groups).sum(:amount)
  end

  validates :name, :icon, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups if user_signed_in?
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-input-container">
    <%=  form.text_field :name, placeholder:"Category Name" %>
  </div>

  <div class="form-input-container">
    <%= form.text_field :icon, placeholder:"Icon Image Url"  %>
  </div>

  <div class="form-submit-container">
    <%= form.submit "SAVE" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="categories-card" id="<%= dom_id group %>">

    <img class="categories-image" src=<%= group.icon %>>
  <p class="categories-name">
        <%= group.name %>
  </p>
  <p class="categories-total">
  <strong>$
    <%= group.total_amount %>
  </strong>
</p>
</div>

app/views/groups/_header.html.erb
<header>
<h2 class="page-title">CATEGORIES</h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false}, class:"log-out-btn"  %>
</header>

app/views/groups/_new_group_header.html.erb
<header>
<%= link_to groups_path do %>
<span class="material-symbols-outlined">
arrow_back
</span>
<% end%>


<h2 class="page-title">NEW CATEGORY</h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false}, class:"log-out-btn"  %>
</header>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
  <% if current_user %>
  <%= render "header" %>
<div id="groups">
  <% @groups.each do |group| %>
      <%= link_to group_expenses_path(group_id: group.id)  do %>
    <%= render group %>
      <%end%>
  <% end %>
</div>

<div class="new-group-btn-container">
<%= link_to "New category", new_group_path, class:"new-group-btn" %>
</div>
<% else %>
<div class="splash-logo-container">
<h1>Moneye</h1>
</div>
<div class="auth-btn-container">
    <%= button_to 'LOG IN',
        new_user_session_path, class: "login-btn",
        method: :get %>
<%= button_to 'SIGN UP',
        new_user_registration_path, class: "sign-up-btn",
        method: :get %>
  <% end %>
  </div>

app/views/groups/new.html.erb
<%= render "new_group_header" %>
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>