config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses_groups
  resources :groups do
  resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "groups#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @group = current_user.groups.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
    @sum = @expenses.sum(:amount)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @group = Group.find(params[:expense][:group_id])
    @expense = @group.expenses.create(name: params[:expense][:name], amount: params[:expense][:amount], user_id: current_user.id)
    respond_to do |format|
      if @expense.save
        format.html { redirect_to groups_path, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # def expense_params
  #   params.permit(:name, :amount, :group_id)
  # end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div class="expenses-card" id="<%= dom_id expense %>">
  <p class="expenses-name">
    <%= expense.name %>
  </p>

  <p class="expense-amount">
  <strong>$
    <%= expense.amount %>
    </strong>
  </p>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: group_expenses_path	) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="expense-input-container">
    <%= form.text_area :name, placeholder:"Bought WinRAR" %>
  </div>

  <div class="expense-input-container">
    <%= form.text_field :amount, placeholder:"How much?" %>
  </div>

    <div class="expense-input-container">
        <%= form.select :group_id, current_user.groups.collect {|group| [group.name, group.id]}, {include_blank: false}, class:"form-select", id:"groupSelect" %>
  </div>

  <div class="expense-input-container">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/_header.html.erb
<header id="transaction-header">
<%= link_to root_path do %>
<span class="material-symbols-outlined">
arrow_back
</span>
<% end%>
<h2 class="page-title">TRANSACTIONS</h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false}, class:"log-out-btn"  %>
</header>

app/views/expenses/_new_expense_header.html.erb
<header>
<%= link_to group_expenses_path do %>
<span class="material-symbols-outlined">
arrow_back
</span>
<% end%>


<h2 class="page-title">NEW TRANSACTION</h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false}, class:"log-out-btn"  %>
</header>

app/views/expenses/_recent_bar.html.erb
<div class="most-recent-container">
<p class="most-recent-text">
ׁׁׁׁ Most recent<br>
·
</p>
</div>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
  <%= render "header" %>
  <%= render "recent_bar" %>
  <div class="total-container">
<p>Total Amount:</p>
<p ><strong> $<%= @sum %></strong></p>
</div>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>

<div class="new-group-btn-container">
<%= link_to "New Transaction", new_group_expense_path, class:"new-group-btn" %>
</div>

app/views/expenses/new.html.erb
<%= render "new_expense_header" %>

<%= render "form", expense: @expense %>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>